---
apiVersion: v1
kind: Pod
metadata:
  labels:
   app: summit
  name: summit
spec:
  volumes:
  - name: summit-www
    hostPath:
      path: /home/kwozyman/src/rh/edge-os/www
      type: Directory
  - name: summit-registry
    persistentVolumeClaim:
      claimName: summit-registry
  containers:
  - image: docker.io/library/httpd:2.4.59
    name: httpd
    ports:
    - containerPort: 80
      hostPort: 8088
    securityContext:
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: summit-www
      readOnly: true
  - image: docker.io/library/registry:2.8.3
    name: registry
    ports:
    - containerPort: 5000
      hostPort: 5000
    volumeMounts:
      - mountPath: /var/lib/registry
        name: summit-registry
