---
apiVersion: v1
kind: Pod
metadata:
  labels:
   app: summit
  name: summit
spec:
  volumes:
  - name: summit-www
    hostPath:
      path: ./config
      type: Directory
  - name: summit-registry
    persistentVolumeClaim:
      claimName: summit-registry
  - name: registry-certs
    hostPath:
      path: ./certs
      type: Directory
  hostname: summit.registry
  containers:
  - image: docker.io/library/httpd:2.4.59
    name: httpd
    ports:
    - containerPort: 80
      hostPort: 8088
    securityContext:
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: summit-www
      readOnly: true
  - image: docker.io/library/registry:2.8.3
    name: registry
    env:
      - name: REGISTRY_HTTP_TLS_CERTIFICATE
        value: /certs/ca.crt
      - name: REGISTRY_HTTP_TLS_KEY
        value: /certs/ca.key
      - name: REGISTRY_HTTP_ADDR
        value: 0.0.0.0:443
    ports:
    - containerPort: 443
      hostPort: 443
    volumeMounts:
      - mountPath: /var/lib/registry
        name: summit-registry
      - mountPath: /certs
        name: registry-certs
